Repository MyMeds-Turing/my_meds_fe, pull requests merged in 2022-07, with the labels that each got.

#6 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation

#7 Create node.js.yml
  .github/workflows/node.js.yml
Labels: CI/CD

#9 Testing/initial cypress setup
  cypress.config.ts
  cypress/e2e/1-getting-started/test.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: Testing

#12 Add initial Nav and Form components
  cypress/e2e/1-getting-started/test.cy.js
  package-lock.json
  package.json
  src/Components/App/App.tsx
  src/Components/Dashboard/Dashboard.tsx
  src/Components/Form/Form.tsx
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.tsx
  src/index.tsx
  src/interfaces.tsx
  src/mockData.tsx
Labels: FE

#14 Setup/search form
  src/Assets/icons/capsule.png
  src/Assets/icons/round-pill.png
  src/Components/App/App.tsx
  src/Components/Form/Form.css
  src/Components/Form/Form.tsx
  src/Components/Form/SearchForm.css
  src/Components/Form/SearchForm.tsx
  src/Components/Form/SubmissionForm.css
  src/Components/Form/SubmissionForm.tsx
  src/Components/Graphic/Graphic.css
  src/Components/Graphic/Graphic.tsx
  src/interfaces.tsx
  src/mockData.tsx
Labels: FE, components

#17 Setup/mutation
  src/Assets/icons/warningSign.png
  src/Components/App/App.tsx
  src/Components/Dashboard/Dashboard.tsx
  src/Components/Dashboard/MedReminder.css
  src/Components/Dashboard/MedReminder.tsx
  src/Components/Form/SearchForm.tsx
  src/Components/Form/SubmissionForm.tsx
  src/GraphQL/Mutations.tsx
  src/GraphQL/Queries.tsx
  src/interfaces.tsx
  src/mockData.tsx
Labels: FE

#25 Feature/cypress
  cypress/e2e/1-getting-started/test.cy.js
  cypress/e2e/addMed.cy.js
  cypress/e2e/dashboard.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/meds-fetch.json
  cypress/utils/graphql-test-utils.js
  package-lock.json
  package.json
  src/Components/Dashboard/MedReminder.tsx
  src/Components/Form/SubmissionForm.tsx
  src/Components/Nav/Nav.tsx
Labels: FE, Testing

#27 Feature/take meds
  src/Components/App/App.tsx
  src/Components/CountdownTimer/CountdownTimer.js
  src/Components/Dashboard/Dashboard.tsx
  src/Components/Dashboard/MedReminder.css
  src/Components/Dashboard/MedReminder.tsx
  src/Components/Form/SearchForm.tsx
  src/Components/Form/SubmissionForm.tsx
  src/Components/Nav/Nav.css
  src/GraphQL/Mutations.tsx
  src/GraphQL/Queries.tsx
Labels: enhancement, FE

#32 Testing/testing refactor
  cypress/e2e/addMed.cy.js
  cypress/e2e/dashboard.cy.js
  src/Components/App/App.tsx
  src/Components/Dashboard/MedReminder.tsx
  src/Components/Form/SubmissionForm.tsx
  src/GraphQL/Mutations.tsx
  src/GraphQL/Queries.tsx
Labels: FE, Testing
